if(NOT DEFINED SDK_LIBRARY OR NOT DEFINED NM_TOOL OR NOT DEFINED EXPECTED_SYMBOLS_FILE)
    message(FATAL_ERROR "SDK export check missing SDK_LIBRARY, NM_TOOL, or EXPECTED_SYMBOLS_FILE")
endif()
execute_process(
    COMMAND "${NM_TOOL}" -D --defined-only "${SDK_LIBRARY}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE symbols
    ERROR_VARIABLE error)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "nm failed: ${error}")
endif()
file(STRINGS "${EXPECTED_SYMBOLS_FILE}" expected)
list(FILTER expected EXCLUDE REGEX "^$")
list(SORT expected)
set(actual "")
string(REPLACE "\n" ";" lines "${symbols}")
foreach(line IN LISTS lines)
    if(line STREQUAL "")
        continue()
    endif()
    string(REGEX MATCH "[^ ]+$" symbol "${line}")
    string(REGEX REPLACE "@@.*$" "" symbol "${symbol}")
    if(symbol STREQUAL "FV1SDK_1.0")
        continue()
    endif()
    if(NOT symbol MATCHES "^fv1_sdk_")
        message(FATAL_ERROR "unexpected non-C SDK symbol: ${symbol}\n${symbols}")
    endif()
    list(APPEND actual "${symbol}")
endforeach()
list(REMOVE_DUPLICATES actual)
list(SORT actual)
if(NOT actual STREQUAL expected)
    message(FATAL_ERROR "SDK export manifest mismatch\nExpected: ${expected}\nActual: ${actual}")
endif()
message(STATUS "SDK shared-library export surface exactly matches candidate manifest")
